// const SET_PRODUCT_NAME = 'SET_PRODUCT_NAME'
const SET_PRODUCTS = 'SET_PRODUCTS'
const SET_PRODUCT_VALUE = 'SET_PRODUCT_VALUE'

export {
    // SET_PRODUCT_NAME,
    SET_PRODUCTS,
    SET_PRODUCT_VALUE,
}
